
// Generated by xt-genmpu.

#include <stdint.h>
#include <xtensa/hal.h>

#if defined (__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#include <assert.h>
#endif

#if defined (__cplusplus)
extern "C"
#endif
const struct xthal_MPU_entry
__xt_mpu_init_table[] __attribute__((section(".ResetHandler.text"))) = {
  XTHAL_MPU_ENTRY(0x00000000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x50000000, 1, XTHAL_AR_RXrx, XTHAL_MEM_WRITEBACK | XTHAL_MEM_OUTER_SHAREABLE), // srom
  XTHAL_MPU_ENTRY(0x51000000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x55500000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_DEVICE), // l2regs
  XTHAL_MPU_ENTRY(0x55501000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x55600000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_WRITEBACK | XTHAL_MEM_OUTER_SHAREABLE), // l2ram
  XTHAL_MPU_ENTRY(0x55700000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x5ffa0000, 1, XTHAL_AR_RWrw, XTHAL_MEM_NON_CACHEABLE), // dram0
  XTHAL_MPU_ENTRY(0x5ffa8000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x5ffc0000, 1, XTHAL_AR_RWrw, XTHAL_MEM_NON_CACHEABLE), // dram1
  XTHAL_MPU_ENTRY(0x5ffc8000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x5ffe0000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_NON_CACHEABLE), // iram0
  XTHAL_MPU_ENTRY(0x5ffe8000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x60000000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_WRITEBACK | XTHAL_MEM_OUTER_SHAREABLE), // sram
  XTHAL_MPU_ENTRY(0x64000000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0xd0000000, 1, XTHAL_AR_RWrw, XTHAL_MEM_DEVICE), // apb
  XTHAL_MPU_ENTRY(0xd0200000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
};

#if defined (__cplusplus)
extern "C"
#endif
const uint32_t __xt_mpu_init_table_size __attribute__((section(".ResetHandler.text"))) = 17;

#if defined (__cplusplus)
extern "C"
#endif
const uint32_t __xt_mpu_init_cacheadrdis __attribute__((section(".ResetHandler.text"))) = 0x000000f3;

#if defined (__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
static_assert(sizeof(__xt_mpu_init_table)/sizeof(__xt_mpu_init_table[0]) == 17, "Incorrect MPU table size");
#endif
